### ISSUE TITLE
Class attributes shadow `__slots__`

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.proxy#1]
In https://bugs.launchpad.net/zope.proxy/+bug/186631, @ctheune reported:

> Define a subclass from `SpecificationDecoratorBase` with slots:
> 
> ``` python
> class MyProxy(SpecificationDecoratorBase):
>     __slots__ = ('foo',)
>     foo = None
> ```
> 
> Now, when using an instance of `MyProxy` the following will happen:
> 
> ``` python
> >> f = MyProxy([])
> >> print f.foo
> None
> >> f.foo = 'bar'
> >> print f.foo
> None
> ```
> 
> When not assigning `foo` as a class attribute, it works. IMHO this isn't exactly intended to work this way, but the tests don't specify anything here.

**Comment by tseaver** [comment]
I don't reproduce this exactly, but the behavior is still odd:

```python
>>> class MyProxy(SpecificationDecoratorBase):
...     __slots__ = ('foo',)
...     foo = None
... 
>>> f = MyProxy([])
>>> print f.foo
None
>>> f.foo = 'bar'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'foo'
```

**Comment by jamadden** [comment]
I'm not sure this is a bug. You get the same basic thing without involving a proxy:

```python
>>> class MyObject(object):
...     __slots__ = ('foo',)
...     foo = None
...
>>> f = MyObject()
>>> print f.foo
None
>>> f.foo = 'bar'
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'MyObject' object attribute 'foo' is read-only
```

The presence of the `foo` class attribute suppresses the creation of the normal slot descriptor for `foo` that would be done by the metaclass:
```python
>>> MyObject.__dict__
{'__module__': '__main__', '__slots__': ('foo',), 'foo': None, '__doc__': None}
# Compare to an absent class attribute
>>> class MyOtherObject(object):
...     __slots__ = ('foo',)
...
>>> MyOtherObject.__dict__
{'foo': <member 'foo' of 'MyOtherObject' objects>, '__slots__': ('foo',), '__module__': '__main__', '__doc__': None}
```

But `__slots__` has already customized the instance layout, and since there's no descriptor, and no `__dict__`,  `foo` is unavailable on the instance. So this behaviour seems reasonable to me, albeit obscure. It matches the wording in language spec on slots:
> `__slots__` are implemented at the class level by creating descriptors (Implementing Descriptors) for each variable name. As a result, *class attributes cannot be used to set default values* for instance variables defined by `__slots__`; otherwise, the class attribute would overwrite the descriptor assignment.

Now, where it gets weird in the proxy case is if the underlying object *can* accept a `foo` attribute. Then, instead of getting set on the proxy object, it gets passed through to the underlying object (and it's still not accessible through the proxy):

```python
>>> class Any(object): pass
...
>>> any = Any()
>>> f = MyObject(any)
>>> f.foo
>>> f.foo = 'bar'
>>> f.foo
>>> any.foo
'bar'
```

I'm not sure if that's a genuine bug, or if we're in corner-cases of the language specification because we're trying to use `__slots__` and class attributes at the same time.

**Comment by tseaver** [comment]
@jamadden I buy the "not-a-bug" argument here.
