### ISSUE TITLE
Tests fail on python 3.6

### ISSUE THREAD

**Issue by luigino** [zopefoundation/zope.proxy#18]
Packaging for openSUSE Tumbleweed, see attached log.
[zope.proxy_py3_test.txt](https://github.com/zopefoundation/zope.proxy/files/1137876/zope.proxy_py3_test.txt)

<details>

```
+ /usr/bin/python3 setup.py -q test
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
E
======================================================================
ERROR: proxy (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: proxy
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/abuild/rpmbuild/BUILD/zope.proxy-4.2.1+git1.g903a662/src/zope/proxy/__init__.py", line 21, in <module>
    from zope.interface import moduleProvides
ModuleNotFoundError: No module named 'zope.interface'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

</details>

**Comment by jamadden** [comment]
`python setup.py test` is prone to this type of failure. That's why we generally [no longer use it](https://github.com/zopefoundation/zope.proxy/commit/6489017129d0117407c2174ca6040f71870fb229). This project doesn't use it anymore in its automated tests (although support for it apparently wasn't completely removed, making it an attractive nuisance). Instead, this project uses zope.testrunner to run its tests [on Travis](https://github.com/zopefoundation/zope.proxy/blob/master/.travis.yml#L17) and via [tox](https://github.com/zopefoundation/zope.proxy/blob/master/tox.ini#L10).  Can you do the same?

**Comment by luigino** [comment]
Thanks, zope-testrunner works for me.

There's just a small glitch I could get around but not understand:
`PYTHONPATH=$(pwd)/build/lib.linux-(etcetera) zope-testrunner --test-path=src -v`
works for 2.7 and 3.4 but not 3.6. The latter requires PYTHONPATH to be the actual installation dir
and vice versa.

Do you reckon this is related to changes to python itself or something else?

Thanks

**Comment by jamadden** [comment]
> The latter requires PYTHONPATH to be the actual installation dir
and vice versa.

I'm not sure I understand what you're saying. It seems like you're saying that if `zope.proxy` is installed non-editably in the environment (`pip install .`), then trying to run `zope.testrunner` against the `src` directory of the checkout (as in the command you gave) works on 2.7 but doesn't work on 3.6.

If I understand correctly, then I have no idea. I cannot duplicate that. The `tox.ini` of this package does a normal (not editable) install of `zope.proxy`, and then runs ` zope-testrunner --test-path=src`, and that works for me with 2.7, 3.4, 3.5 and 3.6. E.g.,:

```
$ tox -e py36
GLOB sdist-make: /zope.proxy/setup.py
py36 inst-nodeps: //zope.proxy/.tox/dist/**zope.proxy-4.3.0.dev0.zip**
py36 installed: alabaster==0.7.10,Babel==2.4.0,certifi==2017.4.17,chardet==3.0.4,docutils==0.13.1,idna==2.5,
  imagesize==0.7.1,Jinja2==2.9.6,MarkupSafe==1.0,Pygments==2.2.0,pytz==2017.2,
  repoze.sphinx.autointerface==0.8,requests==2.18.1,six==1.10.0,snowballstemmer==1.2.1,
  Sphinx==1.6.3,sphinxcontrib-websupport==1.0.1,urllib3==1.21.1,zope.component==4.3.0,zope.event==4.2.0,
  zope.exceptions==4.1.0,zope.i18nmessageid==4.1.0,zope.interface==4.4.2,
  zope.location==4.0.3,
  **zope.proxy==4.3.0.dev0**,
  zope.schema==4.5.0,zope.security==4.1.1,zope.testrunner==4.7.0
py36 runtests: PYTHONHASHSEED='542339343'
py36 runtests: commands[0] | zope-testrunner --test-path=src
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Ran 209 tests with 0 failures, 0 errors and 16 skipped in 0.020 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
...
$ file .tox/py36/lib/python3.6/site-packages/zope/proxy/__init__.py
.tox/py36/lib/python3.6/site-packages/zope/proxy/__init__.py: Python script, ASCII text executable
$ .tox/py36/bin/python --version
Python 3.6.1
```

**Comment by luigino** [comment]
Sorry, I omitted a few essential details:
to build for rpm packaging I get the tarball from pypi, build and install it with setuptools, but I have no internet connection during this process, so I can't use tox.

Basically:

```
python-$pyversion setup.py build
python-$pyversion setup.py install --root=foo
PYTHONPATH=$(pwd)/build/lib.linux-$arch-$pyversion zope-testrunner-$pyversion --test-path=src -v
```
works for python 2.7 and 3.4 but for 3.6 I need to set PYTHONPATH=foo.
By the way, the same happens with zope.configuration and zope.schema.

This is probably an unsanctioned way of building zope modules, but if you have
any idea, openSUSE users will be happy  :smile:

**Comment by jamadden** [comment]
I have to admit I'm not very familiar with the `--root` option of `setup.py install`, so I'm not sure what the layout of the directory structure would be after that. But it looks here like you're not even relying on the install step, because you're pointing to the `build/` subdirectory produced by the first step. I also don't know how you established the initial environment---I do know that it's not recommended to mix `pip install` with `setup.py install` due to differences in the way they manage packages (especially namespace packages).

Really, I wouldn't *necessarily* expect that (putting the build directory on sys.path) to work at all, under any python version, for any namespace package, *if* there are other packages in that namespace installed. Namespace packages are unfortunately something of a black art, and the details depend on which version of Python is in use as well as which version of setuptools is installed. In my experience, though, (and this is anecdotal and others can surely provide other data points), it's best to keep namespace packages all installed together (in the same way) and not try to point to them outside the installation tree. This is due to some combination of .pth files and ordering of sys.path, plus whether or not there's an `__init__.py` that does the `pkg_resources` dance or not present (recent versions of setuptools don't always install that). So typically `zope.testrunner` needs to be installed in the same environment in the same fashion that the package is (that's part of why we've been dropping `setup.py test`---this all started to break with 3.5, IIRC).

You might find that this process works on 3.6 if you either drop the `--root` and install in the normal `site-packages` directory, but I assume you have isolation reasons for needing to do that. It's vaguely possible that if `$PWD/src` is on the `$PYTHONPATH` instead of the build directory it might also work.

I don't know how much help any of that was. I'm unfortunately not as much of a packaging expert as I would like to be, and things are very much still in flux in that area with updated pip and setuptools (and flit and PEP 517 and ...) so what I do learn quickly becomes outdated.

**Comment by mgedmin** [comment]
IIRC you need the code under test to be importable from Python when you're using zope-testrunner, as zope-testrunner itself doesn't add anything to sys.path.

I would be tempted to try

    virtualenv -p python-$ver --system-site-packages foo
    foo/bin/pip install .
    foo/bin/python -m zope.testrunner --test-path=src -v

to set up a temporary virtualenv that inherits all the system site packages (where you have all the dependencies of zope.proxy and also zope.testrunner already installed from RPMs, yes? so pip won't need to go to the Internet, which is not accessible anyway) and also makes zope.proxy available without touching your system site-packages or playing with $PYTHONPATH.

I also wonder if it wouldn't be better to run the tests on the built RPM rather than on the source tree.  (I think Ubuntu's autopkgtests do that.)

**Comment by luigino** [comment]
The pip/virtualenv trick seems to be working. I wonder though if it makes sense to check other binaries than then ones I'll be installing.

Will have to try and virtualenv everything if possible.

**Comment by luigino** [comment]
I've just discovered the virtualenv thing works on 2.7 and 3.6 but not 3.4.

**Comment by luigino** [comment]
In the end the only reliable way I've found is to build, install and then run the tests from a separate rpm package. This solution is acceptable to me and OBS people.

Thanks for all your help.
